[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker-image/docker/Dockerfile.prod"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "learn-x-backend"
type = "web"
port = 8000

[[services]]
name = "celery-worker"
type = "worker"
command = "celery -A src.celery_app worker --loglevel=info"

[[services]]
name = "celery-beat"
type = "worker"
command = "celery -A src.celery_app beat --loglevel=info"