[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.debug"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/v2/health"
healthcheckTimeout = 60