-- Migration: Remove problematic embedding trigger
-- This trigger was making HTTP calls inside database transactions, causing:
-- 1. Transaction locking
-- 2. Poor performance (25/min vs 5000/min needed)
-- 3. Potential deadlocks

-- Drop the trigger that fires on chunk insert/update
DROP TRIGGER IF EXISTS auto_embed_file_chunks ON file_chunks;

-- Drop the function that queues embeddings
DROP FUNCTION IF EXISTS queue_file_chunk_embeddings();

-- Drop the cron job that processes embeddings
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        PERFORM cron.unschedule('process-embeddings');
    END IF;
END $$;

-- Drop the message queue for embeddings
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgmq') THEN
        PERFORM pgmq.drop_queue('embedding_jobs');
    END IF;
END $$;

-- Drop the embedding processing function
DROP FUNCTION IF EXISTS process_embedding_jobs(INT);

-- Drop the embedding requests tracking table
DROP TABLE IF EXISTS embedding_requests;

-- Drop the HTTP response processing function  
DROP FUNCTION IF EXISTS process_embedding_responses();

-- Add comment to file_chunks table about new embedding strategy
COMMENT ON TABLE file_chunks IS 'Stores document chunks. Embeddings are now generated by external workers, not database triggers.';

-- Keep the embedding column and pgvector functionality
-- We're only removing the automatic trigger-based generation